import "./globals.css";
import Header from '@/src/components/header'
import Provider from '@/context/provider';
import Footer from '@/src/components/footer'
import { Metadata } from "next";
import { SessionProvider } from "next-auth/react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <Provider session>
      <body className="bg-blanc">
        <Header />
        {children}
        <Footer />
      </body>
      </Provider>
      
    </html>
  )
}