import "./globals.css";
import Header from '@/src/components/header'
<<<<<<< HEAD
import Provider from '@/context/provider';
import Footer from '@/src/components/footer'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
=======
import Footer from "@/src/components/footer";
>>>>>>> e97667fc04a7d39ad5a98349b9b0885637fe2799

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
<<<<<<< HEAD
  return (
    <html lang="fr">
      <Provider session>
=======
  return(
    <html>
>>>>>>> e97667fc04a7d39ad5a98349b9b0885637fe2799
      <body className="bg-blanc">
        <Header />
        {children}
        <Footer />
      </body>
      </Provider>
      
    </html>
  )
<<<<<<< HEAD
}
=======
}
>>>>>>> e97667fc04a7d39ad5a98349b9b0885637fe2799
